
-- query get user
select USER_ID,USER_GROUP_ID,BRANCH_CODE,USER_NAME,USER_LOGIN,USER_PASSWORD,USER_ISLOGON,USER_ISLOGON_DATE,USER_STATUS,USER_CREATED_BY,USER_CREATED_DATE,USER_CREATED_TIME,ID_UNIT,ID_DIVISION,ID_REGION,EMAIL,BRANCH_ID,NOTIF_EVENT,SOURCE_BANK,LOGIN_TYPE from [SYSTEM_USER]
select USER_ID,USER_GROUP_ID,BRANCH_CODE,USER_NAME,USER_LOGIN,USER_PASSWORD,USER_ISLOGON,USER_ISLOGON_DATE,USER_STATUS,USER_CREATED_BY,USER_CREATED_DATE,USER_CREATED_TIME,ID_UNIT,ID_DIVISION,ID_REGION,EMAIL,BRANCH_ID,NOTIF_EVENT,SOURCE_BANK,LOGIN_TYPE from [SYSTEM_USER] WHERE USER_ID = '2'

-- query get group
select USER_GROUP_ID, USER_GROUP_CODE, USER_GROUP_NAME,USER_GROUP_STATUS from SYSTEM_USER_GROUP
select USER_GROUP_ID, USER_GROUP_CODE, USER_GROUP_NAME,USER_GROUP_STATUS from SYSTEM_USER_GROUP WHERE USER_GROUP_ID = '2'

-- query get branch code kantor cabang
if branch code = ID0019356 {
	return branch_id & ID_REGION & ID_UNIT & ID_DIVISION
}

-- query get branch code kantor wilayah
if branch code = ID0019356 {
	return branch_id & ID_REGION & ID_UNIT & ID_DIVISION
}

-- query get branch code kantor pusat
if branch code = ID0019356 {
	return ID_REGION & ID_UNIT & ID_DIVISION
}


jdbc:sqlserver://10.250.33.140:1433;DatabaseName=BSM_CHMS;